name:                snek
version:             0.1.0.0
github:              "alicereuter/snek"
license:             BSD3
author:              "Alice Reuter"
maintainer:          "alice@alicereuter.com"
copyright:           "2019 Alice Reuter"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/snek#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  snek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - brick
    - snek

tests:
  snek-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - snek
